### ISSUE TITLE
Problems porting to python3

### ISSUE THREAD

**Issue by RyanPaulMcKenna** [georgethrax/collada2obj#1]
Traceback (most recent call last):
  File "/home/ozwald/collada2obj/lxdae2obj.py", line 123, in <module>
    source_float_dict[source.attrib['id']] = map(lambda i:float_array[i:i+3], range(0,len(float_array),3))
TypeError: object of type 'map' has no len()
Traceback (most recent call last):
  File "/home/ozwald/collada2obj/lxdae2obj.py", line 123, in <module>
    source_float_dict[source.attrib['id']] = map(lambda i:float_array[i:i+3], range(0,len(float_array),3))
TypeError: object of type 'map' has no len()
Traceback (most recent call last):
  File "/home/ozwald/collada2obj/lxdae2obj.py", line 123, in <module>
    source_float_dict[source.attrib['id']] = map(lambda i:float_array[i:i+3], range(0,len(float_array),3))
TypeError: object of type 'map' has no len()

**Comment by kwesiRutledge** [comment]
Quick follow-up on this, @RyanPaulMcKenna : I've created a new fork of the repo that runs *most* of the features from this branch. You can find it [here](https://github.com/kwesiRutledge/collada2obj). Stay tuned to that fork as I think the full set of features will be finished in the next few days.

The
